version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  codelab-auth-mongodb:
    environment:
      CODELAB_USER: $CODELAB_USER
      CODELAB_PASS: $CODELAB_PASS
      INIT_DUMP: data.js
    build: codelab-auth-service/mongodb
    ports:
      - 20184:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  codelab-article-mongodb:
    environment:
      CODELAB_USER: $CODELAB_USER
      CODELAB_PASS: $CODELAB_PASS
      INIT_DUMP: data.js
    build: codelab-article-service/mongodb
    ports:
      - 20183:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  codelab-account-mongodb:
    environment:
      CODELAB_USER: $CODELAB_USER
      CODELAB_PASS: $CODELAB_PASS
      INIT_DUMP: data.js
    build: codelab-account-service/mongodb
    ports:
      - 20182:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
